-- Money-table backup
-- Generated: 2026-10-02T05:17:46.595Z
-- Database: postgresql://postgres:***@localhost:5433/krovaa_chat

-- users: 13 row(s)
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (10, 'xyz', 'xoyepak704@dyleris.com', '$2a$10$X19WoLD2.IcRmz7OAdxhru1LtR7ldUCrHBuDn29uiDn4dhEjCC.wO', 'hmm', NULL, '', NULL, NULL, 'client', 'active', NULL, '2026-06-19T15:14:35.219Z', '2026-06-19T15:50:29.233Z', '', '', 'Student', FALSE, 900, NULL, '+916849587067', '', '', 'Male', 22, 'OFFER_SERVICE', '', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'individual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 0, 1, 0);
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (2, 'krovaa', 'admin@krovaa.com', '$2a$10$wnag5BCHTzOys6ZWQX8i.OPV6/NrFTVn7INnBInNrWjEuab.XEcoS', 'Krovaa', NULL, NULL, NULL, NULL, 'admin', 'active', NULL, '2026-05-29T07:00:53.372Z', '2026-05-29T07:00:53.372Z', '', '', NULL, FALSE, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'individual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 0, 0, 0);
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (4, 'mark', 'mark@example.com', '$2a$10$wnag5BCHTzOys6ZWQX8i.OPV6/NrFTVn7INnBInNrWjEuab.XEcoS', 'Mark Solomons', NULL, NULL, NULL, NULL, 'client', 'active', NULL, '2026-05-29T07:00:53.409Z', '2026-05-29T07:00:53.409Z', '', '', NULL, FALSE, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'individual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 0, 0, 0);
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (5, 'sara', 'sara@example.com', '$2a$10$wnag5BCHTzOys6ZWQX8i.OPV6/NrFTVn7INnBInNrWjEuab.XEcoS', 'Sara Lee', NULL, NULL, NULL, NULL, 'client', 'active', NULL, '2026-05-29T07:00:53.419Z', '2026-05-29T07:00:53.419Z', '', '', NULL, FALSE, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'individual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 0, 0, 0);
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (6, 'devteam', 'dev@example.com', '$2a$10$wnag5BCHTzOys6ZWQX8i.OPV6/NrFTVn7INnBInNrWjEuab.XEcoS', 'Dev Team', NULL, NULL, NULL, NULL, 'vendor', 'active', NULL, '2026-05-29T07:00:53.428Z', '2026-05-29T07:00:53.428Z', '', '', NULL, FALSE, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'individual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 0, 0, 0);
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (8, 'ABC', 'savoyi3254@fanchatu.com', '$2a$10$dCMZNeg1Ppjpy6FtElzpm./4yzCbuX35LXr1Itn2/a/fK62QBkgfe', 'DEF', NULL, 'i am b tech gradutae', NULL, NULL, 'client', 'active', NULL, '2026-06-05T13:21:46.642Z', '2026-06-05T13:34:36.336Z', '', '', 'Web Developer', FALSE, 10000, NULL, '+917898644444', '', '', 'Female', 22, 'OFFER_SERVICE', '', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'individual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 0, 0, 0);
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (3, 'alice', 'alice@example.com', '$2a$10$wnag5BCHTzOys6ZWQX8i.OPV6/NrFTVn7INnBInNrWjEuab.XEcoS', 'Alice MurrayAlice', NULL, '', NULL, NULL, 'client', 'active', NULL, '2026-05-29T07:00:53.398Z', '2026-06-07T05:02:50.149Z', '', '', 'Software Developer', FALSE, 0, NULL, '+919876543210', '', '', 'Male', 21, 'OFFER_SERVICE', '', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'individual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 0, 0, 0);
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (11, 'shadow', 'xagalic133@ocuser.com', '$2a$10$lUHdC7i.3HQgdyBY2afM6Oxzv0x7A3jQ.WkXo0PQkhoqKQicpEccS', 'shark', NULL, '', NULL, NULL, 'client', 'active', NULL, '2026-06-19T16:56:22.306Z', '2026-06-19T17:03:44.982Z', '', '', 'Business Owner', FALSE, 0, NULL, '+919898457785', '', '', 'Male', 22, 'RUN_BUSINESS', '', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'business', 'fbewjfebr', 'Startup', 'fedjfek', 'dsnfjked', 'Karnataka', '576124', 'dshfe', NULL, NULL, '', 0, 0, 0);
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (1, 'imganeshnayak', '', '$2a$10$KFcKr4Jngo7MAik9lZ/3kuH0BYVGWFDd1oYnUdrCbgxVwQnV6MggW', 'Ganesh', NULL, 'Nothing to say', 'https://res.cloudinary.com/dahotkqpi/image/upload/v1780049035/krovaa/avatars/h2ewy90pxnyqjs9bnyrz.png', NULL, 'client', 'active', NULL, '2026-05-29T07:00:41.756Z', '2026-06-05T04:19:14.346Z', '', '', 'Web Developer', FALSE, 4175.6, NULL, '7676377870', 'Banglore', '576124', 'Male', 22, 'OFFER_SERVICE', 'java,mongo,py', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'individual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 0, 0, 0);
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (7, 'Ganesh', 'itzganeshnayak@gmail.com', '$2a$10$urq8vdcaT3SHbt4Y/qvBs.QPlI.m.wpJCiDc5eUT79TZDib0LLhVy', 'Ganesh', NULL, 'I am a software developer', 'https://res.cloudinary.com/dahotkqpi/image/upload/v1780064574/krovaa/avatars/lqkuioi9mu2yeewuzm9h.png', 'https://res.cloudinary.com/dahotkqpi/image/upload/v1780064771/krovaa/profiles/xxc4gmcfopf5iluowsqv.jpg', 'client', 'active', NULL, '2026-05-29T14:15:58.200Z', '2026-10-02T05:14:00.224Z', '[]', '', 'web developer', FALSE, 58655.32, NULL, '+917676377870', 'Udupi', '576124', 'Male', 22, 'OFFER_SERVICE', 'java,python,mongo', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'individual', NULL, NULL, 'Kukkehalli, Udupi, Udupi District', 'Udupi', 'KARNATAKA', '576124', NULL, NULL, NULL, 'Udupi', 0, 0, 0);
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (13, 'ramesh', 'ganeshnayak8175@gmail.com', '$2a$10$.5iv4r.YL90EEd1Er3wXhulxOR/OioOyX.OnTL4DJCNNzspwqpEle', 'ramesh', NULL, 'none', NULL, NULL, 'client', 'active', NULL, '2026-07-22T05:28:48.968Z', '2026-10-02T05:14:00.232Z', '', '', 'Business Owner', FALSE, 20081.92, NULL, '07676377870', '', '', 'Male', 22, 'RUN_BUSINESS', '', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'business', 'Ganesh Nayak', 'Enterprise', 'Kukkehalli main road 3-205', 'UDUPI', 'KARNATAKA', '576124', NULL, 'Ganesh_Nayak_13_423439', '85874504', '', 0, 1, 0);
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (9, 'cde', 'lixole1974@fanchatu.com', '$2a$10$Zcz8vrzpv2m3kQ2AgosAmOi1Sx4rCV7O2knoRHUmD4hH49UV735S.', 'efg', NULL, '', NULL, NULL, 'client', 'active', NULL, '2026-06-08T05:35:40.134Z', '2026-06-08T05:42:47.093Z', '', '', 'Student', FALSE, 28820, NULL, '+917676377870', '', '', 'Female', 21, 'HIRE_PROFESSIONALS', '', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'individual', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', 0, 0, 0);
INSERT INTO "users" (id, "username", "email", "password", "displayName", "shareId", "bio", "avatarUrl", "coverPhotoUrl", "role", "status", "telegramId", "createdAt", "updatedAt", "socialLinks", "permissions", "profession", "verified", "walletBalance", "razorpayContactId", "phoneNumber", "city", "pincode", "gender", "age", "userGoal", "skills", "kycStatus", "kycVerifiedAt", "kycRejectionReason", "kycData", "twoFactorEnabled", "twoFactorMethod", "twoFactorSecret", "dataConsentGiven", "consentGivenAt", "dataRetentionUntil", "erasureRequested", "erasureRequestedAt", "dailyTransferLimit", "monthlyTransferLimit", "dailyTransferUsed", "monthlyTransferUsed", "lastTransferResetDay", "accountType", "businessName", "businessType", "businessAddress", "businessCity", "businessState", "businessPincode", "businessLandmark", "shiprocketPickupName", "shiprocketPickupId", "location", "jobsDone", "reviews", "earned") VALUES (12, 'SAM', 'tapive8766@jctoto.com', '$2a$10$jkkHDKuojOGvbEbMUcXqH.9uc59VaOnl4WCJ10hfVXUrURz1N1JLq', 'sam', NULL, '', NULL, NULL, 'client', 'active', NULL, '2026-06-30T13:35:43.045Z', '2026-06-30T13:36:27.592Z', '', '', 'Business Owner', FALSE, 0, NULL, '+917895994986', '', '', 'Male', 22, 'RUN_BUSINESS', '', 'not_submitted', NULL, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, NULL, FALSE, NULL, 50000, 500000, 0, 0, NULL, 'business', 'nothing', 'Other', 'Kukkehalli, Udupi, Udupi District', 'UDUPI', 'Karnataka', '576124', NULL, NULL, NULL, '', 0, 0, 0);

-- wallet_transactions: 19 row(s)
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (1, 1, 'credit', 1952.8, 1952.8, 'pay_SvCNMfgUjfRTFE', 'Wallet Top-up via Razorpay (Net: ₹1952.80)', '2026-05-29T13:36:57.430Z', NULL);
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (2, 7, 'credit', 1952.8, 1952.8, 'pay_SvD5MNG3SsKysc', 'Wallet Top-up via Razorpay (Net: ₹1952.80)', '2026-05-29T14:18:35.506Z', NULL);
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (3, 1, 'credit', 1952.8, 3905.6, 'pay_SvG6QiAYu1e081', 'Wallet Top-up via Razorpay (Net: ₹1952.80)', '2026-05-29T17:15:45.880Z', NULL);
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (4, 7, 'debit', -200, 1752.8, 'chat_7_1_1780380686999', 'Escrow creation: Java web developer', '2026-06-05T04:05:39.020Z', '[object Object]');
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (5, 7, 'debit', -100, 1652.8, 'chat_7_1_1780380686999', 'Escrow creation: new projectn', '2026-06-05T04:09:10.070Z', '[object Object]');
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (6, 1, 'escrow_release', 180, 4085.6, 'deal_1', 'Payment release: Java web developer (100%).', '2026-06-05T04:12:26.837Z', '[object Object]');
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (7, 1, 'escrow_release', 81, 4166.6, 'deal_2', 'Payment release: new projectn (90%).', '2026-06-05T04:18:25.942Z', '[object Object]');
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (8, 1, 'escrow_release', 8.1, 4174.700000000001, 'deal_2', 'Payment release: new projectn (9%).', '2026-06-05T04:18:39.074Z', '[object Object]');
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (9, 1, 'escrow_release', 0.9, 4175.6, 'deal_2', 'Payment release: new projectn (1%).', '2026-06-05T04:19:14.348Z', '[object Object]');
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (10, 7, 'credit', 48820, 50472.8, 'pay_Sxy1H0y8bZpENZ', 'Wallet Top-up via Razorpay (Net: ₹48820.00)', '2026-06-05T13:31:24.358Z', NULL);
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (11, 9, 'credit', 48820, 48820, 'pay_Sz1dUircQxhbCa', 'Wallet Top-up via Razorpay (Net: ₹48820.00)', '2026-06-08T05:42:37.158Z', NULL);
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (12, 7, 'debit', -1000, 39472.8, '7_10', 'Paid Escrow Deal: new product', '2026-06-19T15:49:05.062Z', '[object Object]');
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (13, 10, 'escrow_release', 900, 900, 'deal_5', 'Final payment release for completed deal: new product.', '2026-06-19T15:50:17.359Z', '[object Object]');
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (14, 7, 'debit', -1000, 38472.8, '7_11', 'Paid Escrow Deal: new product', '2026-06-19T17:39:58.557Z', '[object Object]');
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (15, 13, 'credit', 9764, 9764, 'pay_TGQwoaT5L3R49S', 'Wallet Top-up via Razorpay (Net: ₹9764.00)', '2026-07-22T05:31:17.768Z', NULL);
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (16, 13, 'escrow_release', 9091.224, 18855.224, 'deal_13', 'Final payment release for completed deal: laptop.', '2026-07-22T06:37:02.675Z', '[object Object]');
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (17, 7, 'credit', 10101.36, 48574.16, '7_13', 'Refund: Order Cancelled - laptop', '2026-07-22T06:53:50.632Z', '[object Object]');
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (18, 13, 'escrow_release', 1226.7, 20081.924, 'deal_14', 'Final payment release for completed deal: fdh.', '2026-07-22T07:28:02.819Z', '[object Object]');
INSERT INTO "wallet_transactions" (id, "userId", "type", "amount", "balance", "reference", "description", "createdAt", "metadata") VALUES (19, 7, 'credit', 10081.16, 58655.32000000001, '7_13', 'Refund: Order Cancelled - new phone', '2026-07-25T17:16:46.890Z', '[object Object]');

-- escrow_deals: 21 row(s)
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (14, '7_13', 7, 13, 'fdh', 'eft

Includes ₹150 shipping fee.', 1363, 100, 'completed', '2026-07-22T07:24:14.481Z', '2026-07-22T07:28:02.791Z', 1363, 'paid', 'order_TGSuJnfRFds4tl', 'pay_TGSupLvzb4Anpa', NULL, FALSE, NULL, NULL, 8, 1, '15x15x10', 'Primary Profile Address', 'AWB_DUMMY_1784705233839', 'delivered', '[object Object],[object Object],[object Object]', 'SR_DUMMY_1784705207473', 'SHP_DUMMY_1784705207473', 'AWB_DUMMY_1784705233839', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 1);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (11, '7_12', 7, 12, 'mobile phone', 'new deal

Includes ₹101.36 shipping fee.', 10101.36, 0, 'active', '2026-07-17T14:27:20.070Z', '2026-07-21T17:09:31.458Z', 10101.36, 'paid', 'order_TGEHS3haPGmFw4', 'pay_TGEJ17NV5RGtGO', NULL, FALSE, NULL, NULL, 6, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, 1);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (2, 'chat_7_1_1780380686999', 7, 1, 'new projectn', 'new', 100, 100, 'completed', '2026-06-05T04:09:10.072Z', '2026-06-05T04:19:14.335Z', 100, 'paid', NULL, NULL, 'none', FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (3, '7_10', 10, 7, 'new', 'none', 1000, 0, 'pending_payment', '2026-06-19T15:15:12.785Z', '2026-06-19T15:15:12.785Z', 0, 'pending', NULL, NULL, NULL, FALSE, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (4, '7_10', 10, 7, 'new', 'none', 9998, 0, 'pending_payment', '2026-06-19T15:39:49.216Z', '2026-06-19T15:39:52.508Z', 0, 'pending', 'order_T3Xh78AxRCOl72', NULL, NULL, FALSE, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (1, 'chat_7_1_1780380686999', 7, 1, 'Java web developer', 'this project is a new for me', 200, 100, 'completed', '2026-06-05T04:05:39.042Z', '2026-07-22T06:32:53.283Z', 200, 'paid', NULL, NULL, 'nothing to be specified', FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'delivered', '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (10, '7_12', 7, 12, 'mobile phone', 'new deal

Includes ₹150 shipping fee.', 10150, 0, 'active', '2026-06-30T14:49:23.641Z', '2026-06-30T14:58:23.619Z', 10150, 'paid', 'order_T7spRzubfxxkd0', 'pay_T7sqSb9xnXAMEk', NULL, FALSE, NULL, NULL, 6, 0.5, 'Large (50x50x40 cm)', 'sam, Kukkehalli, Udupi, Udupi District, UDUPI, KA - 576124 (Ph: 7895994986)', 'AWB_DUMMY_1782831503617', 'pickup_scheduled', '[object Object],[object Object]', 'SR_DUMMY_1782831455745', 'SHP_DUMMY_1782831455745', 'AWB_DUMMY_1782831503617', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 1);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (5, '7_10', 7, 10, 'new product', 'nothing', 1000, 100, 'completed', '2026-06-19T15:49:02.267Z', '2026-06-19T15:50:17.333Z', 1000, 'paid', NULL, NULL, NULL, FALSE, NULL, NULL, 3, 1, 'Medium (30x30x20 cm)', 'none', 'AWB-6090786866', 'delivered', '[object Object],[object Object],[object Object]', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (6, '7_11', 7, 11, 'new product', 'nothing', 1000, 0, 'active', '2026-06-19T17:39:47.264Z', '2026-06-19T17:40:55.157Z', 1000, 'paid', NULL, NULL, NULL, FALSE, NULL, NULL, 4, 1, 'Small (15x15x10 cm)', 'gnkfgbgfjk', 'AWB-3166132474', 'delivered', '[object Object],[object Object],[object Object]', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (8, '7_10', 7, 10, 'new product', 'nothing

Includes ₹150 shipping fee.', 1150, 0, 'pending_payment', '2026-06-29T05:50:12.478Z', '2026-06-29T05:50:12.478Z', 0, 'pending', NULL, NULL, NULL, FALSE, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (7, '7_11', 7, 11, 'new product', 'nothing', 1000, 0, 'active', '2026-06-25T04:41:59.972Z', '2026-06-29T07:06:36.444Z', 1000, 'paid', 'order_T7MH75CCH2wYu6', 'pay_T7MHmWVSvrc08C', NULL, FALSE, NULL, NULL, 4, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (9, '7_12', 7, 12, 'new prodct', 'new description  of the prodct

Includes ₹150 shipping fee.', 1150, 0, 'active', '2026-06-30T13:41:46.378Z', '2026-06-30T13:42:59.710Z', 1150, 'paid', 'order_T7rYp767cFatHE', 'pay_T7rZcU8vtwv1mU', NULL, FALSE, NULL, NULL, 5, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (12, '7_12', 7, 12, 'new prodct', 'new description  of the prodct

Includes ₹81.16 shipping fee.', 1081.16, 0, 'cancelled', '2026-07-17T14:28:04.431Z', '2026-07-17T14:29:22.124Z', 0, 'pending', NULL, NULL, NULL, FALSE, NULL, NULL, 5, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, 1);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (13, '7_13', 7, 13, 'laptop', 'Product details for laptops include technical attributes such as display size, processor type, memory capacity, and battery life. For example, a specific laptop model might feature a 13-inch display, an Nvidia Tegra K1 (armV7) CPU, 16GB SSD flash memory, 2GB RAM, and a Lithium-Ion battery that runs for 7 hours during online streaming tests.

Includes ₹101.36 shipping fee.', 10101.36, 100, 'cancelled', '2026-07-22T05:51:02.524Z', '2026-07-22T06:53:50.639Z', 10101.36, 'refunded', 'order_TGRIF0l4KU6fXP', 'pay_TGRJEts9BdtVDc', NULL, FALSE, NULL, NULL, 7, 1, '15x15x10', 'Primary Profile Address', 'null', 'null', '[object Object],[object Object],[object Object]', '1468028046', '1464257577', 'AWB_DUMMY_1784701328439', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', 1);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (18, '7_13', 7, 13, 'new phone', 'nothing to describe

Includes ₹81.16 shipping fee.', 10081.16, 0, 'active', '2026-07-25T17:18:12.135Z', '2026-07-25T17:19:17.900Z', 10081.16, 'paid', 'order_THobPZqBVqcWHS', 'pay_THoc3yQI3toeP9', NULL, FALSE, NULL, NULL, 10, NULL, NULL, NULL, NULL, NULL, '', '1475168380', '1471395015', NULL, NULL, 1);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (15, '7_13', 7, 13, 'new phone', 'nothing to deliver

Includes ₹101.36 shipping fee.', 1101.36, 0, 'active', '2026-07-23T14:05:15.489Z', '2026-07-23T14:07:56.488Z', 1101.36, 'paid', 'order_TGyFMBmA42RBQ4', 'pay_TGyG57Z0shT5tt', NULL, FALSE, NULL, NULL, 9, 1, '15x15x10', 'Primary Profile Address', '1091395807354', 'pickup_scheduled', '[object Object],[object Object]', '1470869537', '1467097904', '1091395807354', 'https://sr-core-cdn.shiprocket.in/label/s/10784725/019f8f4d-eb24-7364-b404-d0611cbeb495.pdf', 1);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (21, '7_13', 7, 13, 'new phone', 'new description

Includes ₹81.16 shipping fee.', 10081.16, 0, 'active', '2026-07-26T13:45:05.769Z', '2026-07-26T13:46:50.919Z', 10081.16, 'paid', 'order_TI9VhrmRSYGdy4', 'pay_TI9WFt4MOQLzHA', NULL, FALSE, NULL, NULL, 11, 1, '15x15x10', 'Primary Profile Address', '371210106715', 'pickup_scheduled', '[object Object],[object Object]', '1476569423', '1472795425', '371210106715', 'https://sr-core-cdn.shiprocket.in/label/s/10784725/716c216786892408159db41d7623026bfinal_labels_amazon.pdf', 1);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (20, '7_13', 7, 13, 'new phone', 'nothing to deliver

Includes ₹81.16 shipping fee.', 1081.16, 0, 'cancelled', '2026-07-26T05:59:02.215Z', '2026-10-02T04:40:12.279Z', 0, 'pending', NULL, NULL, NULL, FALSE, NULL, NULL, 9, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, 1);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (19, '7_13', 7, 13, 'new phone', 'nothing to describe

Includes ₹81.16 shipping fee.', 10081.16, 0, 'active', '2026-07-26T05:00:14.880Z', '2026-07-26T05:21:21.275Z', 10081.16, 'paid', 'order_TI0Yz1akIPybwJ', 'pay_TI0ZeGjPypT85L', NULL, FALSE, NULL, NULL, 10, 1, '15x15x10', 'Primary Profile Address', '371202486955', 'pickup_scheduled', '[object Object],[object Object]', '1475670828', '1471897264', '371202486955', 'https://sr-core-cdn.shiprocket.in/label/s/10784725/5e015eeed9b237d04235d0d466170208final_labels_amazon.pdf', 1);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (17, '7_13', 7, 13, 'new phone', 'nothing to describe

Includes ₹81.16 shipping fee.', 10081.16, 0, 'cancelled', '2026-07-25T17:07:09.345Z', '2026-07-25T17:16:46.901Z', 10081.16, 'refunded', 'order_THoPndLlWrDhA5', 'pay_THoQRcHpqmPYMI', NULL, FALSE, NULL, NULL, 10, 1, '15x15x10', 'Primary Profile Address', NULL, NULL, '', '1475149531', '1471376170', NULL, NULL, 1);
INSERT INTO "escrow_deals" (id, "chatId", "clientId", "vendorId", "title", "description", "totalAmount", "releasedPercent", "status", "createdAt", "updatedAt", "paidAmount", "paymentStatus", "razorpayOrderId", "razorpayPaymentId", "terms", "isSplitDeal", "teamId", "splitConfig", "dealListingId", "shippingWeight", "shippingDimensions", "pickupAddress", "trackingId", "shippingStatus", "shippingEvents", "shiprocketOrderId", "shiprocketShipmentId", "shiprocketAwbCode", "shippingLabelUrl", "shippingAddressId") VALUES (16, '7_13', 7, 13, 'new phone', 'nothing to deliver

Includes ₹81.16 shipping fee.', 1081.16, 0, 'cancelled', '2026-07-23T14:20:04.401Z', '2026-07-25T17:17:52.216Z', 0, 'pending', NULL, NULL, NULL, FALSE, NULL, NULL, 9, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, 1);

-- escrow_transactions: 22 row(s)
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (1, 1, 0, 20, 'platform_fee', '2026-06-05T04:05:39.062Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (2, 2, 0, 10, 'platform_fee', '2026-06-05T04:09:10.076Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (3, 1, 100, 180, 'Payment released (Platform fee already deducted at creation)', '2026-06-05T04:12:26.821Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (4, 2, 90, 81, 'Payment released (Platform fee already deducted at creation)', '2026-06-05T04:18:25.934Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (5, 2, 9, 8.1, 'Payment released (Platform fee already deducted at creation)', '2026-06-05T04:18:39.070Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (6, 2, 1, 0.9, 'Payment released (Platform fee already deducted at creation)', '2026-06-05T04:19:14.334Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (7, 5, 0, 100, 'platform_fee', '2026-06-19T15:49:05.079Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (8, 5, 100, 900, 'Final release upon buyer confirmation', '2026-06-19T15:50:17.346Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (9, 6, 0, 100, 'platform_fee', '2026-06-19T17:39:58.585Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (10, 7, 0, 100, 'platform_fee', '2026-06-29T07:06:36.448Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (11, 9, 0, 115, 'platform_fee', '2026-06-30T13:42:59.720Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (12, 10, 0, 1015, 'platform_fee', '2026-06-30T14:57:35.678Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (13, 11, 0, 1010.136, 'platform_fee', '2026-07-21T17:09:31.462Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (14, 13, 0, 1010.136, 'platform_fee', '2026-07-22T05:52:33.221Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (15, 13, 100, 9091.224, 'Final release upon buyer confirmation', '2026-07-22T06:37:02.655Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (16, 14, 0, 136.3, 'platform_fee', '2026-07-22T07:26:47.321Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (17, 14, 100, 1226.7, 'Final release upon buyer confirmation', '2026-07-22T07:28:02.801Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (18, 15, 0, 110.136, 'platform_fee', '2026-07-23T14:06:34.697Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (19, 17, 0, 1008.116, 'platform_fee', '2026-07-25T17:08:17.644Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (20, 18, 0, 1008.116, 'platform_fee', '2026-07-25T17:19:17.348Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (21, 19, 0, 1008.116, 'platform_fee', '2026-07-26T05:01:19.835Z');
INSERT INTO "escrow_transactions" (id, "dealId", "percent", "amount", "note", "createdAt") VALUES (22, 21, 0, 1008.116, 'platform_fee', '2026-07-26T13:46:19.914Z');

-- payout_requests: 0 row(s)

-- transactions: 4 row(s)
INSERT INTO "transactions" (id, "userId", "type", "label", "amount", "description", "status", "relatedId", "relatedModel", "createdAt", "updatedAt") VALUES (1, 7, 'debit', 'Project Escrow Funding', 10000, 'Funded Collab Project: new proje', 'completed', '1', 'ProjectListing', '2026-06-05T13:31:40.584Z', '2026-06-05T13:31:40.584Z');
INSERT INTO "transactions" (id, "userId", "type", "label", "amount", "description", "status", "relatedId", "relatedModel", "createdAt", "updatedAt") VALUES (2, 8, 'credit', 'Collab Milestone Released', 5000, 'Milestone release: Final Delivery (50%)', 'completed', '1', 'ProjectListing', '2026-06-05T13:34:36.332Z', '2026-06-05T13:34:36.332Z');
INSERT INTO "transactions" (id, "userId", "type", "label", "amount", "description", "status", "relatedId", "relatedModel", "createdAt", "updatedAt") VALUES (3, 8, 'credit', 'Collab Milestone Released', 5000, 'Milestone release: Final Delivery (50%)', 'completed', '1', 'ProjectListing', '2026-06-05T13:34:36.342Z', '2026-06-05T13:34:36.342Z');
INSERT INTO "transactions" (id, "userId", "type", "label", "amount", "description", "status", "relatedId", "relatedModel", "createdAt", "updatedAt") VALUES (4, 9, 'debit', 'Project Escrow Funding', 20000, 'Funded Collab Project: new job', 'completed', '3', 'ProjectListing', '2026-06-08T05:42:47.104Z', '2026-06-08T05:42:47.104Z');
